platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!
supports_swift_versions '>= 5.0'

target 'SBCamera_Example' do
  pod 'SBCamera', :path => '../'

  target 'SBCamera_Tests' do
    inherit! :search_paths

    
  end
end
